#!/usr/bin/env python
# -*- coding: utf-8 -*- 
FLIP_RESOURCE = """
a - ɐ
b - q
c - ɔ
d - p
e - ə,∃
f - ɟ,Ⅎ
g - ƃ
h - ɥ,H
i - ı,I
j - ɾ
k - ʞ
l - l
m - ɯ
n - u
o - o
p - d
q - b
r - ɹ
s - s 
t - ʇ
u - n
v - ʌ
w - ʍ
x - x
y - ʎ
z - z"""

flip_map = {}
for record in FLIP_RESOURCE[1:].split('\n'):
    record = record.strip()
    ch_key, ch_value = record.split(' - ')
    values = ch_value.split(',')
    flip_map[ch_key] = {'lower': values[0]}
    if len(values)>1:
        flip_map[ch_key]['upper'] = values[1]
    else:
        flip_map[ch_key]['upper'] = values[0]
        
import sys
p = sys.stdout.write

input_text = sys.argv[1]
for input_ch in input_text[::-1]:
    key = input_ch.lower()
    if key in flip_map:
        flip_tuple = flip_map[key]
        if input_ch.isupper(): p(flip_tuple['upper'])
        else: p(flip_tuple['lower'])
    else: p(input_ch)
