#!/usr/bin/env python
# -*- coding: utf-8 -*- 
import sys

FLIP_RESOURCE = """
a - ɐ
b - q
c - ɔ
d - p
e - ə,∃
f - ɟ,Ⅎ
g - ƃ
h - ɥ,H
i - ı,I
j - ɾ
k - ʞ
l - l
m - ɯ
n - u
o - o
p - d
q - b
r - ɹ
s - s 
t - ʇ
u - n
v - ʌ
w - ʍ
x - x
y - ʎ
z - z"""

def prepare_flip_map():
  ret = {}
  for record in FLIP_RESOURCE[1:].split('\n'):
    record = record.strip()
    ch_key, ch_value = record.split(' - ')
    values = ch_value.split(',')
    ret[ch_key] = {'lower': values[0]}
    if len(values)>1:
      ret[ch_key]['upper'] = values[1]
    else:
      ret[ch_key]['upper'] = values[0]
  return ret 
      
FLIP_MAP = prepare_flip_map()

if __name__=='__main__':
  p = sys.stdout.write
  for input_ch in ' '.join(sys.argv[1:])[::-1]:
    key = input_ch.lower()
    if key in FLIP_MAP:
      value = FLIP_MAP[key]
      if input_ch.isupper(): 
        p(value['upper'])
      else: 
        p(value['lower'])
    else: p(input_ch)
